config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "posts#index"
  namespace :posts do
    resources :avatars, only: :index
  end
  resources :posts

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_fill: [120, 120, gravity: :center]
  end

  validates :title, presence: true

  validates :avatar, content_type: ["image/png", "image/jpeg", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/posts/avatars_controller.rb
class Posts::AvatarsController < ApplicationController
  def index
    # 画像が添付されている投稿に制限するため joins(:avatar_attachment)
    # N+1問題を回避するため with_attached_avatar
    @posts = Post.joins(:avatar_attachment).with_attached_avatar.order(id: :asc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.order(id: :asc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><span style="color: red;"><%= msg %></span></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to "投稿一覧", posts_path %> <%= link_to "投稿画像一覧", posts_avatars_path %> <%= link_to "新規投稿", new_post_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Active Storage Sample App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/error_messages", object: @post %>
<%= form_with model: @post do |form| %>
  <p>
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </p>
  <p>
    <%= form.file_field :avatar, accept: "image/png,image/jpeg,image/gif" %>
  </p>
  <div>
    <%= form.submit "送信" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <th scope="row"><%= post.id %></th>
  <td><%= post.title %></td>
  <td>
    <%= link_to "詳細", post %>
    <%= link_to "編集", edit_post_path(post) %>
    <%= link_to "削除", post, data: { turbo_method: :delete, turbo_confirm: "削除してよろしいですか？" } %>
  </td>
</tr>

app/views/posts/avatars/_post.html.erb
<%= link_to post do %>
  <%= image_tag post.avatar.variant(:thumb) %>
<% end %>

app/views/posts/avatars/index.html.erb
<h1>投稿画像一覧</h1>
<%= render partial: "posts/avatars/post", collection: @posts %>

app/views/posts/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<table>
  <thead>
  <tr>
    <th scope="col">ID</th>
    <th scope="col">タイトル</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <%= render @posts %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
<p>タイトル : <%= @post.title %></p>
<% if @post.avatar.attached? %>
  <div>
    <%= image_tag @post.avatar %>
  </div>
<% end %>
<hr>
<p>
  <%= link_to "編集", edit_post_path(@post) %>
  <%= link_to "削除", @post, data: { turbo_method: :delete, turbo_confirm: "削除してよろしいですか？" } %>
</p>
<hr>
<p><%= link_to "投稿一覧", posts_path %></p>